# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
  end

  config.vm.define "backup" do |b|
    b.vm.hostname = "backup"
    b.vm.network("private_network", ip: '192.168.56.160')
    b.vm.disk :disk, size: "2GB", name: "disk1"
    b.vm.provision "shell", path: "script.sh"
  end

  config.vm.define "client" do |c|
    c.vm.hostname = "client"
    c.vm.network("private_network", ip: '192.168.56.150')
  end
end

