# -*- mode: ruby -*-
# vim: set ft=ruby :

boxes = [
  { :name => "web",
    :ip => "192.168.56.10",
  },
  { :name => "log",
    :ip => "192.168.56.15",
  },
]

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1512
    vb.cpus = 2
  end

  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
    end  
  end  

  config.vm.provision "shell", inline: <<-SHELL
    echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
    echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf > /dev/null
  SHELL

end

