# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
  end

  config.vm.define "backup" do |web|
    web.vm.hostname = "backup"
  end

  config.vm.define "client" do |db|
    db.vm.hostname = "client"
  end
end

