- name: VPN
  hosts: all
  # gather_facts: false
  become: true
  tasks:
  - name: copy resolv.conf
    template: 
      src: resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644

  - name: install base tools
    apt:
      name:
        - openvpn
        - iperf3
        - selinux-utils
      state: present
      update_cache: true

  - name: Get SELinux mode
    ansible.builtin.shell: 'getenforce'
    register: command_output
  
  - name: Set SELinux to permissive mode
    ansible.builtin.shell: 'setenforce 0'
    when: command_output.stdout != 'Disabled'

  - name: Execute a simple shell command
    ansible.builtin.shell: 'openvpn --genkey secret /etc/openvpn/static.key'
    when: (ansible_hostname == "server")

  - name: Set up OpenVPN on server
    template: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
    with_items:
      - { src: "server.conf", dest: "/etc/openvpn/server.conf", mode: "0644" }
      - { src: "openvpn@.service", dest: "/etc/systemd/system/openvpn@.service", mode: "0644" }
    when: (ansible_hostname == "server")

- hosts: server
  become: true
  tasks:
  - name: Fetch file from source_server to control machine
    ansible.builtin.fetch:
      src: /etc/openvpn/static.key
      dest: /tmp/
      flat: yes

- hosts: client
  become: true
  tasks:
  - name: Copy file from control machine to destination_server
    ansible.builtin.copy:
      src: /tmp/static.key
      dest: /etc/openvpn/static.key

- name: VPN continue
  hosts: all
  # gather_facts: false
  become: true
  tasks:
  - name: Set up OpenVPN on client
    template: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
    with_items:
      - { src: "server.conf1", dest: "/etc/openvpn/server.conf", mode: "0644" }
      - { src: "openvpn@.service", dest: "/etc/systemd/system/openvpn@.service", mode: "0644" }
    when: (ansible_hostname == "client")

  - name: OpenVPN enable and start
    ansible.builtin.service:
      name: openvpn@server
      enabled: true
      state: started
