- name: OpenVPN tun mode
  hosts: server
  # gather_facts: false
  become: true
  tasks:
  - name: copy resolv.conf
    template: 
      src: resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644

  - name: install base tools
    apt:
      name:
        - openvpn
        - easy-rsa
        - selinux-utils
      state: present
      update_cache: true

  - name: Get SELinux mode
    ansible.builtin.shell: 'getenforce'
    register: command_output
  
  - name: Set SELinux to permissive mode
    ansible.builtin.shell: 'setenforce 0'
    when: command_output.stdout != 'Disabled'

  - name: Set up OpenVPN on server
    template: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
    with_items:
      - { src: "server.conf.ras", dest: "/etc/openvpn/server.conf", mode: "0644" }
      - { src: "openvpn@.service", dest: "/etc/systemd/system/openvpn@.service", mode: "0644" }

  - name: Execute ras.sh
    ansible.builtin.script: ras.sh

  - name: restart openvpn
    service:
      name: openvpn@server
      state: restarted
      enabled: true      


